#22 tf bash update

diff --git a/bin/generate_tfrc_credentials b/bin/generate_tfrc_credentials
--- a/bin/generate_tfrc_credentials
+++ b/bin/generate_tfrc_credentials
@@ -1,22 +1,22 @@
 #!/usr/bin/env bash
 
-# Define the target directory and file
-target_dir="/home/gitpod/.terraform.d"
-target_file="${target_dir}/credentials.tfrc.json"
+# Define target directory and file
+TARGET_DIR="/home/gitpod/.terraform.d"
+TARGET_FILE="${TARGET_DIR}/credentials.tfrc.json"
 
 # Check if TERRAFORM_CLOUD_TOKEN is set
 if [ -z "$TERRAFORM_CLOUD_TOKEN" ]; then
-  echo "Error: TERRAFORM_CLOUD_TOKEN environment variable is not set."
-  exit 1
+    echo "Error: TERRAFORM_CLOUD_TOKEN environment variable is not set."
+    exit 1
 fi
 
-# Create the target directory if it doesn't exist
-if [ ! -d "$target_dir" ]; then
-  mkdir -p "$target_dir"
+# Check if directory exists, if not, create it
+if [ ! -d "$TARGET_DIR" ]; then
+    mkdir -p "$TARGET_DIR"
 fi
 
-# Create the credentials.tfrc.json file
-cat > "$target_file" <<EOF
+# Generate credentials.tfrc.json with the token
+cat > "$TARGET_FILE" << EOF
 {
   "credentials": {
     "app.terraform.io": {
@@ -26,5 +26,4 @@ cat > "$target_file" <<EOF
 }
 EOF
 
-echo "$target_file file has been created with the provided token."
-
+echo "${TARGET_FILE} has been generated."
diff --git a/bin/set_tf_alias b/bin/set_tf_alias
--- a/bin/set_tf_alias
+++ b/bin/set_tf_alias
@@ -1,15 +1,17 @@
 #!/usr/bin/env bash
 
-# Define the alias
-alias_to_add='alias tf="terraform"'
+# Check if the alias already exists in the .bash_profile
+grep -q 'alias tf="terraform"' ~/.bash_profile
 
-# Check if the alias already exists in .bash_profile
-if grep -q "$alias_to_add" ~/.bash_profile; then
-  echo "Alias 'tf' already exists in ~/.bash_profile."
+# $? is a special variable in bash that holds the exit status of the last command executed
+if [ $? -ne 0 ]; then
+    # If the alias does not exist, append it
+    echo 'alias tf="terraform"' >> ~/.bash_profile
+    echo "Alias added successfully."
 else
-  # Append the alias to .bash_profile
-  echo "$alias_to_add" >> ~/.bash_profile
-  echo "Alias 'tf' added to ~/.bash_profile"
-  # Apply the changes immediately to the current session
-  source ~/.bash_profile
+    # Inform the user if the alias already exists
+    echo "Alias already exists in .bash_profile."
 fi
+
+# Optional: source the .bash_profile to make the alias available immediately
+source ~/.bash_profile
